# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: XRobot Doc
email: 2592509183@qq.com
description: >- # this means to ignore newlines until "baseurl:"
  XRobot Doc
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://x-robots-org.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  x-robots-org

# Build settings
markdown: kramdown
remote_theme: rundocs/jekyll-rtd-theme
# theme: jekyll-theme-slate
# https://github.com/rundocs/jekyll-rtd-theme
# 
# remote_theme: pages-themes/slate
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: rundocs/jekyll-rtd-theme@v2.0.10
# remote_theme: rundocs/jekyll-rtd-theme
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-feed
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links

readme_index:
  with_frontmatter: true
